#! /bin/bash
#
# Usage:
#  build-base
#
# This program builds the ds-res-base-onbuild image that forms the base image
# for CyVerse Data Store resource server images.
#

readonly BaseDir=$(dirname $(readlink --canonicalize "$0"))


main()
{
  "$BaseDir"/base/irods-netcdf-build/build centos7
  "$BaseDir"/irods-setavu-plugin/build centos7
  docker build --tag ds-res-base-onbuild "$BaseDir"
}


set -e

main
