#! /bin/bash


show_help()
{
  cat <<'EOF'

build

Usage:
 build [options] <tag> <script-dir>

Builds a docker image containing a resource server configured for the CyVerse
Data Store. It assumes the Dockerfile is named 'Dockerfile' and is in the
CONTEXT directory. If there is no Dockerfile, it will use a default one.

It also generates two scripts. `auth-clerver` authenticates the
clerver user with the IES, and `start-irods` starts the resource server inside
the the docker container.

Parameters:
 <tag>         the docker image tag
 <script-dir>  the directory where the scripts will be written: defaults to
               current working directory

Options:
 -c, --context CONTEXT  The docker build context: default current working
                        directory

 -h, --help  show help and exit

Environment Variables:
 CYVERSE_DS_CLERVER_USER       (optional) the name of the rodsadmin user
                               representing the resource server within the
                               zone: default 'ipc_admin'
 CYVERSE_DS_CONTROL_PLANE_KEY  the encryption key required for communicating
                               over the iRODS grid control plane.
 CYVERSE_DS_NEGOTIATION_KEY    the encryption key shared by the zone for
                               advanced negotiation during client connections
 CYVERSE_DS_RES_NAME           the name of the storage resource that will be
                               served
 CYVERSE_DS_RES_SERVER         the FQDN or address used by the IES and other
                               resource servers to communicate with this one
 CYVERSE_DS_RES_VAULT          (optional) the host directory where the container
                               will mount the vault: default '<home>/vault',
                               where <home> is the home directory of the user
                               starting the docker container
 CYVERSE_DS_ZONE_KEY           the shared secret used during server-to-server
                               communication
EOF
}


main()
{
  if ! opts=$(getopt --name build --options c:h --longoptions context:,help -- "$@")
  then
    show_help >&2
    return 1
  fi

  eval set -- "$opts"

  while true
  do
    case "$1" in
      -c|--context)
        context="$2"
        shift 2
        ;;
      -h|--help)
        show_help
        return 0
        ;;
      --)
       shift
       break
       ;;
      *)
        show_help >&2
        return 1
        ;;
    esac
  done

  if [ "$#" -lt 1 ]
  then
    printf 'An image tag is required.\n' >&2
    show_help >&2
    return 1
  fi

  local tag="$1"

  if [ "$#" -ge 2 ]
  then
    local scriptDir="$2"
  else
    local scriptDir="$(pwd)"
  fi

  if [ -z "$context" ]
  then
    context=.
  fi

  check_env CYVERSE_DS_CLERVER_PASSWORD
  check_env CYVERSE_DS_CONTROL_PLANE_KEY
  check_env CYVERSE_DS_NEGOTIATION_KEY
  check_env CYVERSE_DS_RES_NAME
  check_env CYVERSE_DS_RES_SERVER
  check_env CYVERSE_DS_ZONE_KEY

  local containerVault=/irods_vault/"$CYVERSE_DS_RES_NAME"
  local hostVault="${CYVERSE_DS_RES_VAULT:-\$HOME/vault}"
  local hostLog="${CYVERSE_DS_LOG_DIR:-\$HOME/log}"
  local user="${CYVERSE_DS_CLERVER_USER:-ipc_admin}"

  mk_image "$context" "$tag" "$user" "$containerVault" >&2

  mk_svc_script "$tag" "$hostLog" "$hostVault" "$containerVault" > "$scriptDir"/irods-svc
  chmod +x "$scriptDir"/irods-svc
}


#
# Checks for the existence of an environment variable. If the variable doesn't
# exist, it writes a message to standard error and returns 1.
#
# Parameter:
#  var  the environment variable to check
#
check_env()
{
  local var="$1"

  if [ -z "${!var}" ]
  then
    printf 'The environment variable %s is not set.\n' "$var" >&2
    show_help >&2
    return 1
  fi
}


#
# Generates the image build command
#
# Parameters:
#  tag             the tag of the image that the command will build
#  user            the clerver user
#  containerVault  the base directory with the container where the files will be
#                  stored
#  defaultResName  the default resource name
#  srcAccess       the docker build args for setting the context or build
#                  commands access
#
mk_build_cmd()
{
  local tag="$1"
  local user="$2"
  local containerVault="$3"
  local defaultResName="$4"
  local srcAccess="$5"

  cat <<EOF
docker build --build-arg CLERVER_USER_NAME="$user" \
             --build-arg DEFAULT_RESOURCE_DIR="$containerVault" \
             --build-arg DEFAULT_RESOURCE_NAME="$defaultResName" \
             --build-arg RS_CNAME="$CYVERSE_DS_RES_SERVER" \
             --tag "$tag" \
             $srcAccess
EOF
}


#
# Build the image.
#
# Parameters:
#  context         the build context
#  tag             the tag to assign to the built image
#  user            the clerver user
#  containerVault  the base directory within the container where the files will
#                  be stored
mk_image()
{
  local context="$1"
  local tag="$2"
  local user="$3"
  local containerVault="$4"

  local defaultResName="$CYVERSE_DS_RES_NAME"Res
  local srcAccess=

  if [ -e "$context"/Dockerfile ]
  then
    srcAccess="'$context'"
  else
    srcAccess="- <<< 'FROM ds-res-base-onbuild'"
  fi

  eval $(mk_build_cmd "$tag" "$user" "$containerVault" "$defaultResName" "$srcAccess")
}


#
# Generate a script for starting a container from the newly build image.
#
# Parameters:
#  tag             the tag of the image to start
#  hostLog         the host directory where teh container will mount
#                  /var/lib/irods/iRODS/server/log
#  hostVault       the host directory where the container will mount its vault
#  containerVault  the base directory within the container where the files will
#                  be stored
#
mk_svc_script()
{
  local tag="$1"
  local hostLog="$2"
  local hostVault="$3"
  local containerVault="$4"

  cat <<EOF
#! /bin/bash
#
# Usage:
#  irods-svc (start|stop)
#
# This script starts or stops a container holding an iRODS resource server
# configured to serve the $CYVERSE_DS_RES_NAME storage resource for the CyVerse
# Data Store.
#

if [ "\$#" -lt 1 ]
then
  printf 'One of the actions "start" or "stop" needs to be provided\n' >&2
  exit 1
fi

action="\$1"

if [ "\$action" = start ]
then
  docker run --detach --rm --tty \\
             --env CLERVER_USER_PASSWORD="$CYVERSE_DS_CLERVER_PASSWORD" \\
             --env CONTROL_PLANE_KEY="$CYVERSE_DS_CONTROL_PLANE_KEY" \\
             --env LOCAL_USER_ID="\$(id --user)" \\
             --env NEGOTIATION_KEY="$CYVERSE_DS_NEGOTIATION_KEY" \\
             --env ZONE_KEY="$CYVERSE_DS_ZONE_KEY" \\
             --hostname rs \\
             --mount type=bind,source='$hostVault',target='$containerVault' \\
             --mount type=bind,source='$hostLog',target=/var/lib/irods/iRODS/server/log \\
             --mount type=tmpfs,destination=/var/lib/irods/iRODS/server/log/proc \\
             --name rs \\
             --publish 1247:1247/tcp \\
             --publish 1248:1248/tcp \\
             --publish 20000-20009:20000-20009/tcp \\
             --publish 20000-20009:20000-20009/udp \\
             '$tag'
elif [ "\$action" = stop ]
then
  docker stop rs
else
  printf 'unknown action "%s"\n' "\$action" >&2
fi
EOF
}


set -e

main "$@"
