#!/bin/bash
#
# Usage:
#  build
#
# This program builds the ds-irods-rs-onbuild image that forms the base image
# for CyVerse Data Store resource server images. Each build is tagged with the
# number ISO 8601 style build time.

readonly ExecName=$(readlink --canonicalize "$0")
readonly BaseDir=$(dirname "$ExecName")


main()
{
  local tag
  tag=$(date --utc '+%Y-%m-%dT%H-%M-%S')

  "$BaseDir"/irods-netcdf-build/build centos7
  "$BaseDir"/irods-setavu-plugin/build centos7
  docker build --tag cyverse/ds-irods-rs-onbuild "$BaseDir"
  docker tag cyverse/ds-irods-rs-onbuild:latest cyverse/ds-irods-rs-onbuild:"$tag"
}


set -e
main
